#!/bin/sh

#
# collect arguments
#
host=$1
service=$2
action=$3

if [ -z "$action" ]; then
    echo "usage: $(basename $0) host service action"
    exit 1
fi

case $action in
    is-enabled) ;;
    status) ;;
    start) ;;
    stop) ;;
    restart) ;;
    *) echo "unsupported service action $action" && exit 1 ;;
esac

#
# use ssh to run command on a remote host?
#
rmtcmd="/usr/share/mackup/util/remotecmd $host"
if [ "$host" = "localhost" ]; then
    rmtcmd=""
fi

#
# check if service is enabled on remote host
#
if [ "$action" = "is-enabled" ]; then
    exec $rmtcmd systemctl -q is-enabled $service
else
    if [ ! $($rmtcmd systemctl -q is-enabled $service) = 0 ]; then
        echo "service $service not enabled" 1>&2
        exit 1
    fi
fi

#
# Run service action
#
if [ "$action" = "status" ]; then
    exec $rmtcmd systemctl status $service 2>&1 1>/dev/null
else
    if [ ! $($rmtcmd systemctl $action $service) = 0 ]; then
        echo "failed to run $action for service $service" 2>&1
        exit 1
    fi
fi
