#!/bin/sh
#
# git backup script for mackup, see mackup(8) 
#
exec 2>&1

if [ -z "$1" ]; then
    cat <<EOF

This script is part of mackup, a backup suite.

Backup a source using git.

Environment variables:

    REMOTE_HOST
        Address or hostname where sources reside

EOF
    exit 1
fi

source="$(dirname $1)/$(basename $1)"
target=$(basename $1)

cpcmd="cp"

if [ ! -z "$REMOTE_HOST" ]; then
    cpcmd="scp"
    source="$REMOTE_HOST:$source"
fi

if [ ! -d "$target.git" ]; then
    $cpcmd -rp "$source" "$target.git"
    (
        cd "$target.git" \
        && git init
    )
else
    $cpcmd -rp "$source"/* "$target.git"
fi

(
    cd "$target.git"
    if [ ! -z "$(git status -s)" ]; then
        git add .
        git commit -m "backing up $source"
    else
        git status
    fi
)
