#!/bin/sh
#
# tar backup script for mackup, see mackup(8) 
#
exec 2>&1

if [ -z "$1" ]; then
    cat <<EOF

This script is part of mackup, a backup suite.

Backup sources using tar.

Environment variables:

    REMOTE_HOST
        Address or hostname where sources reside

    TAR_OPTS
        Custom list of options (overrides default of '-v', '-c' is always used)

    TAR_BZIP2
        If exists, bzip the archive (-j)

    TAR_GZIP
        If exists, gzip the archive (-z)

EOF
    exit 1
fi

source="$(dirname $1)/$(basename $1)"
target=$(basename $1)
opts="-v"
ext="tar"

if [ ! -z "$TAR_OPTS" ]; then
    opts=$TAR_OPTS
fi

if [ ! -z "$TAR_BZIP2" ]; then
    opts="$opts -j"
    ext="$ext.bz2"
elif [ ! -z "$TAR_GZIP" ]; then
    opts="$opts -z"
    ext="$ext.gz"
fi

if [ ! -z "$REMOTE_HOST" ]; then
    exec ssh $REMOTE_HOST tar $opts -c "$source" > "$target.$ext"
else
    exec tar $opts -cf "$target.$ext" "$source"
fi
